name: bachlorThesis
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - annotated-types=0.7.0
  - backoff=2.2.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - cairo=1.18.4
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.4.3
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - contourpy=1.3.3
  - cycler=0.12.1
  - distro=1.9.0
  - double-conversion=3.3.1
  - einops=0.8.1
  - eval-type-backport=0.2.2
  - eval_type_backport=0.2.2
  - featuretools=1.31.0
  - filelock=3.19.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.60.1
  - freetype=2.14.1
  - fsspec=2025.9.0
  - graphite2=1.3.14
  - h2=4.3.0
  - harfbuzz=12.1.0
  - hf-xet=1.1.8
  - holidays=0.81
  - hpack=4.1.0
  - huggingface_hub=0.35.3
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-resources=6.5.2
  - importlib_resources=6.5.2
  - intel-openmp=2024.2.1
  - jinja2=3.1.6
  - joblib=1.5.2
  - khronos-opencl-icd-loader=2024.10.24
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250512.1
  - libblas=3.9.0
  - libboost=1.88.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang13=21.1.3
  - libdeflate=1.24
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libglib=2.86.0
  - libgomp=15.2.0
  - libiconv=1.18
  - libintl=0.22.5
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblightgbm=4.6.0
  - liblzma=5.8.1
  - libopenblas=0.3.30
  - libpng=1.6.50
  - libprotobuf=6.31.1
  - libsqlite=3.50.4
  - libtiff=4.7.1
  - libtorch=2.7.1
  - libuv=1.51.0
  - libvulkan-loader=1.4.328.1
  - libwebp-base=1.6.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxgboost=3.0.5
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxslt=1.1.43
  - libzlib=1.3.1
  - lightgbm=4.6.0
  - markupsafe=3.0.3
  - matplotlib=3.10.7
  - matplotlib-base=3.10.7
  - mkl=2024.2.2
  - monotonic=1.6
  - mpmath=1.3.0
  - munkres=1.1.4
  - networkx=3.5
  - numpy=2.3.3
  - opencl-headers=2025.06.13
  - openjpeg=2.5.4
  - openssl=3.5.4
  - optree=0.17.0
  - packaging=25.0
  - pandas=2.3.3
  - pcre2=10.46
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.4.0
  - posthog=6.7.6
  - psutil=7.1.0
  - pthread-stubs=0.4
  - py-xgboost=3.0.5
  - pybind11=3.0.1
  - pybind11-global=3.0.1
  - pycparser=2.22
  - pydantic=2.11.10
  - pydantic-core=2.33.2
  - pydantic-settings=2.11.0
  - pyparsing=3.2.5
  - pyside6=6.9.3
  - pysocks=1.7.1
  - python=3.11.13
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.1.1
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytorch=2.7.1
  - pytz=2025.2
  - pyyaml=6.0.3
  - qhull=2020.2
  - qt6-main=6.9.3
  - requests=2.32.5
  - scikit-learn=1.6.1
  - scipy=1.16.2
  - setuptools=80.9.0
  - six=1.17.0
  - sleef=3.9.0
  - sympy=1.14.0
  - tabpfn=2.2.1
  - tabpfn-common-utils=0.2.2
  - tbb=2021.8.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tornado=6.5.2
  - tqdm=4.67.1
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ucrt=10.0.26100.0
  - unicodedata2=16.0.0
  - urllib3=2.5.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - woodwork=0.31.0
  - xgboost=3.0.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - zipp=3.23.0
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - attrs==25.4.0
      - bleach==6.2.0
      - duckdb==1.4.0
      - frozenlist==1.8.0
      - kaggle==1.7.4.5
      - lightning-utilities==0.15.2
      - multidict==6.7.0
      - pooch==1.8.2
      - propcache==0.4.1
      - protobuf==6.32.1
      - pyarrow==21.0.0
      - pytabkit==1.7.2
      - python-slugify==8.0.4
      - pytorch-lightning==2.6.0
      - relbench==1.1.0
      - text-unidecode==1.3
      - torchmetrics==1.8.2
      - webencodings==0.5.1
      - yarl==1.22.0
prefix: C:\Users\kunjo\anaconda3\envs\bachlorThesis
