name: bachlorThesis2
channels:
  - conda-forge
  - defaults
dependencies:
  - _libavif_api=1.3.0
  - _openmp_mutex=4.5
  - aom=3.9.1
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - cairo=1.18.4
  - cloudpickle=3.1.2
  - colorama=0.4.6
  - contourpy=1.3.3
  - cycler=0.12.1
  - dav1d=1.2.1
  - expat=2.7.3
  - featuretools=1.31.0
  - fontconfig=2.15.0
  - fonttools=4.61.1
  - freeglut=3.8.0
  - freetype=2.14.1
  - fribidi=1.0.16
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - holidays=0.87
  - icu=73.2
  - importlib-resources=6.5.2
  - importlib_resources=6.5.2
  - joblib=1.5.3
  - jpeg=9e
  - khronos-opencl-icd-loader=2024.10.24
  - kiwisolver=1.4.9
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250127.0
  - libavif=1.3.0
  - libavif16=1.3.0
  - libblas=3.11.0
  - libboost=1.88.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libclang13=21.1.7
  - libdeflate=1.22
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libglib=2.84.4
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libiconv=1.18
  - libkrb5=1.21.3
  - liblapack=3.11.0
  - liblightgbm=4.6.0
  - libopenjpeg=2.5.4
  - libpng=1.6.53
  - libpq=17.6
  - libre2-11=2024.07.02
  - libtiff=4.7.1
  - libwebp-base=1.6.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxgboost=3.1.2
  - libxml2=2.13.9
  - libxslt=1.1.43
  - libzlib=1.3.1
  - lightgbm=4.6.0
  - llvm-openmp=21.1.8
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - mkl=2025.3.0
  - munkres=1.1.4
  - mysql-common=9.3.0
  - mysql-libs=9.3.0
  - numpy=1.26.4
  - opencl-headers=2025.06.13
  - openjpeg=2.5.4
  - openssl=3.6.0
  - packaging=25.0
  - pandas=2.3.3
  - pcre2=10.46
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - psutil=7.2.0
  - py-xgboost=3.1.2
  - pyparsing=3.3.1
  - pyside6=6.9.2
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.3
  - python_abi=3.11
  - pytz=2025.2
  - qhull=2020.2
  - qtbase=6.9.2
  - qtdeclarative=6.9.2
  - qtshadertools=6.9.2
  - qtsvg=6.9.2
  - qttools=6.9.2
  - qtwebchannel=6.9.2
  - qtwebengine=6.9.2
  - qtwebsockets=6.9.2
  - rav1e=0.7.1
  - re2=2024.07.02
  - setuptools=80.9.0
  - six=1.17.0
  - snappy=1.2.2
  - sqlite=3.51.0
  - svt-av1=3.1.2
  - tbb=2022.3.0
  - threadpoolctl=3.6.0
  - tk=8.6.15
  - tornado=6.5.4
  - tqdm=4.67.1
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - unicodedata2=17.0.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - woodwork=0.31.0
  - xgboost=3.1.2
  - xz=5.6.4
  - zipp=3.23.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.12.0
      - attrs==25.4.0
      - backoff==2.2.1
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - distro==1.9.0
      - datasets==2.19.2
      - duckdb==1.4.3
      - einops==0.8.1
      - eval-type-backport==0.3.1
      - filelock==3.20.1
      - frozenlist==1.8.0
      - fsspec==2025.12.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.2.3
      - idna==3.11
      - jinja2==3.1.6
      - lightning-utilities==0.15.2
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - multidict==6.7.0
      - networkx==3.6.1
      - platformdirs==4.5.1
      - pooch==1.8.2
      - posthog==6.9.3
      - propcache==0.4.1
      - pyarrow==14.0.2
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-settings==2.12.0
      - pytabkit==1.7.2
      - python-dotenv==1.2.1
      - pytorch-lightning==2.6.0
      - pyyaml==6.0.3
      - relbench==1.1.0
      - requests==2.32.5
      - ruff==0.14.10
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - shellingham==1.5.4
      - sympy==1.13.1
      - tabpfn==6.2.0
      - tabpfn-common-utils==0.2.12
      - torch==2.5.1+cu121
      - torchaudio==2.5.1+cu121
      - torchmetrics==1.8.2
      - torchvision==0.20.1+cu121
      - typer-slim==0.21.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.6.2
      - yarl==1.22.0
prefix: C:\Users\kunjo\anaconda3\envs\bachlorThesis2
